### ISSUE TITLE
No documentation or recorder not supported.

### ISSUE THREAD

**Issue by Slasherss1** [chvolkmann/voicemeeter-remote-python#2]
Is recorder supported by this api? If it is please add it to `readme.md`.

**Comment by chvolkmann** [comment]
Hey! It currently isn't supported.

Here are some pointers on implementing it:
- The method `VMRemote#set()` can be used to directly modify parameters.
- According to the [C API docs](https://download.vb-audio.com/Download_CABLE/VoicemeeterRemoteAPI.pdf) you're looking for the parameters of the form `recorder.play`, `recorder.stop`, etc.

Hope this helps, pull requests are welcome! :slightly_smiling_face:

**Comment by Slasherss1** [comment]
Thank you.
