### ISSUE TITLE
vmr.inputs[1].label returns nothing

### ISSUE THREAD

**Issue by yamato-deer** [chvolkmann/voicemeeter-remote-python#5]
I tried __main.py__ ("Usage" in Readme), but ```vmr.inputs[1].label``` returns nothing, and I don't know what "label" is.
What value is expected to return ?

**Comment by LunaMeadows** [comment]
![image](https://user-images.githubusercontent.com/38821657/89052054-beaf6e80-d31a-11ea-9c87-5d823df053c5.png)
This is the label, if you right click to set a name, what ever you set it to will be what is returned. If you do not set it, it will return a blank string.

**Comment by yamato-deer** [comment]
Oh, I didn't know!
After setting the label, it was displayed correctly.
Thanks! 
I also want to know how to get device name (It's "Web(Virtual Audio Cable) in the image you attached ).
This python wrapper doesn't seem to contain method which can get device name.
I added ```device = str_prop('device')``` under ```label = str_prop('Label')``` in input.py and　
ran the following code.
(`__main.py__`)
```
dev = vmr.inputs[0].device
print(dev)
```
However, I got the following error message:
```
Traceback (most recent call last):
  File "C:/Users/fumia/voicemeeter-remote-python/__main__.py", line 15, in <module>
    dev = vmr.inputs[0].device
  File "C:\Users\fumia\voicemeeter-remote-python\voicemeeter\strip.py", line 40, in getter
    return self.get(param, string=True)
  File "C:\Users\fumia\voicemeeter-remote-python\voicemeeter\strip.py", line 12, in get
    return self._remote.get(f'{self.identifier}.{param}', **kwargs)
  File "C:\Users\fumia\voicemeeter-remote-python\voicemeeter\remote.py", line 82, in get
    self._call('GetParameterStringW', param, ct.byref(buf))
  File "C:\Users\fumia\voicemeeter-remote-python\voicemeeter\remote.py", line 31, in _call
    raise VMRDriverError(fn_name, retval)
voicemeeter.errors.VMRDriverError: VMR#VBVMR_GetParameterStringW() returned -1

Process finished with exit code 1
```
What's wrong?

**Comment by LunaMeadows** [comment]
Give me a few to try some trouble shooting on my side. Will let you know if I can figure that out.

**Comment by yamato-deer** [comment]
Thank you! If you can solve it, please let me know later.

**Comment by LunaMeadows** [comment]
Looks like the VM documentation is not correct. To get the device name, use device.name. device = str_prop('device.name') should be the correct code.

**Comment by yamato-deer** [comment]
Oh, it's true! It worked!
Thank you very much!!!!!

**Comment by LunaMeadows** [comment]
Welcome. I hope the creator comes back and fixes these issues soon. Have had to modify a couple things already just to get it working but don't see the creator fixing anything any time soon.

**Comment by yamato-deer** [comment]
I agree. I was referring to your pull request as well (time.sleep). I was stuck with the same error.
I too hope the creators come back and fix these issues soon.
