### ISSUE TITLE
how to call voicmeeter.remote multiple times?

### ISSUE THREAD

**Issue by Phoenix-64** [chvolkmann/voicemeeter-remote-python#8]
```
import voicemeeter


def toggle_mute(mute):
    with voicemeeter.remote('potato', delay=0.125) as vmr:
        print(vmr.get("Strip[0].Mute", string=False))
        vmr.set("Strip[0].Mute", mute)
    return


toggle_mute(0)
print("somthing")
toggle_mute(1)

```

Here I get a 
> voicemeeter.errors.VMRDriverError: VMR#VBVMR_Login() returned -2

I think that I have to somehow call the __exit__ function but have no idea how.
The error comes from remote.py line 29

**Comment by LunaMeadows** [comment]
I ran into a similar issue, the issue is that you can only call one instance of the voicemeeter.remote with how the code is setup. https://github.com/LunaMeadows/voicemeeter-remote-python/tree/patch-3 has that issue fixed in the remote.py. If you use the updated code there, this is an example to mute input 0.

> with voicemeeter.remote('potato') as vmr:
>	pass
>
>vmr.inputs[0].mute = false

**Comment by Phoenix-64** [comment]
Thank you, what does the pass do?

**Comment by LunaMeadows** [comment]
Pass in python just means that the function/method does nothing and continues on with the code. You can't leave it blank or it it doesn't think it is a valid function/method.

**Comment by Phoenix-64** [comment]
Hm. 
```
import voicemeeter

with voicemeeter.remote('potato', delay=0.125) as vmr:
    pass

vmr.inputs[0].mute = False
```

Here I get this error? 
```
Traceback (most recent call last):
  File "D:\Programme\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Programme\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/ArduinoSerialRead/vocimeeter_test.py", line 6, in <module>
    vmr.inputs[0].mute = False
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\strip.py", line 34, in setter
    return self.set(param, 1 if val else 0)
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\strip.py", line 15, in set
    self._remote.set(f'{self.identifier}.{param}', val, **kwargs)
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\remote.py", line 95, in set
    self._call('SetParameterFloat', param, ct.c_float(float(val)))
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\remote.py", line 27, in _call
    retval = getattr(dll, fn_name)(*args)
OSError: exception: access violation reading 0x000001E8A5A40004
python-BaseException
```

Without the delay I get this error:
```
Traceback (most recent call last):
  File "D:\ArduinoSerialRead\vocimeeter_test.py", line 3, in <module>
    with voicemeeter.remote('potato') as vmr:
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\remote.py", line 135, in __enter__
    self._login()
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\remote.py", line 34, in _login
    self._call('Login')
  File "D:\ArduinoSerialRead\env\lib\site-packages\voicemeeter\remote.py", line 30, in _call
    time.sleep(self.delay)
TypeError: an integer is required (got type NoneType)
```

**Comment by LunaMeadows** [comment]
what does the remote.py file look like?

**Comment by Phoenix-64** [comment]
import ctypes as ct
import time
import abc

from .driver import dll
from .errors import VMRError, VMRDriverError
from .input import InputStrip
from .output import OutputBus
from . import kinds
from . import profiles
from .util import merge_dicts

class VMRemote(abc.ABC):
  """ Wrapper around Voicemeeter Remote's C API. """
  def __init__(self, delay=.015):
    self.delay = delay
    self.cache = {}

  def _call(self, fn, *args, check=True, expected=(0,)):
    """
    Runs a C API function.
    
    Raises an exception when check is True and the
    function's return value is not 0 (OK).
    """
    fn_name = 'VBVMR_' + fn
    retval = getattr(dll, fn_name)(*args)
    if check and retval not in expected:
      raise VMRDriverError(fn_name, retval)
    time.sleep(self.delay)
    return retval

  def _login(self):
    self._call('Login')
  def _logout(self):
    self._call('Logout')
  
  @property
  def type(self):
    """ Returns the type of Voicemeeter installation (basic, banana, potato). """
    buf = ct.c_long()
    self._call('GetVoicemeeterType', ct.byref(buf))
    val = buf.value
    if val == 1:
      return 'basic'
    elif val == 2:
      return 'banana'
    elif val == 3:
      return 'potato'
    else:
      raise VMRError(f'Unexpected Voicemeeter type: {val}')

  @property
  def version(self):
    """ Returns Voicemeeter's version as a tuple (v1, v2, v3, v4) """
    buf = ct.c_long()
    self._call('GetVoicemeeterVersion', ct.byref(buf))
    v1 = (buf.value & 0xFF000000) >> 24
    v2 = (buf.value & 0x00FF0000) >> 16
    v3 = (buf.value & 0x0000FF00) >> 8
    v4 = (buf.value & 0x000000FF)
    return (v1, v2, v3, v4)

  @property
  def dirty(self):
    """ True iff UI parameters have been updated. """
    val = self._call('IsParametersDirty', expected=(0,1))
    return (val == 1)
  
  def get(self, param, string=False):
    """ Retrieves a parameter. """
    param = param.encode('ascii')
    if not self.dirty:
      if param in self.cache:
        return self.cache[param]

    if string:
      buf = (ct.c_wchar * 512)()
      self._call('GetParameterStringW', param, ct.byref(buf))
    else:
      buf = ct.c_float()
      self._call('GetParameterFloat', param, ct.byref(buf))
    val = buf.value
    self.cache[param] = val
    return val
  
  def set(self, param, val):
    """ Updates a parameter. """
    param = param.encode('ascii')
    if isinstance(val, str):
      if len(val) >= 512:
        raise VMRError('String is too long')
      self._call('SetParameterStringW', param, ct.c_wchar_p(val))
    else:
      self._call('SetParameterFloat', param, ct.c_float(float(val)))

  def show(self):
    """ Shows Voicemeeter if it's hidden. """
    self.set('Command.Show', 1)
  def shutdown(self):
    """ Closes Voicemeeter. """
    self.set('Command.Shutdown', 1)
  def restart(self):
    """ Restarts Voicemeeter's audio engine. """
    self.set('Command.Restart', 1)

  def apply(self, mapping):
    """ Sets all parameters of a dict. """
    for key, submapping in mapping.items():
      strip, index = key.split('-')
      index = int(index)
      if strip in ('in', 'input'):
        target = self.inputs[index]
      elif strip in ('out', 'output'):
        target = self.outputs[index]
      else:
        raise ValueError(strip)
      target.apply(submapping)
  
  def apply_profile(self, name):
    try:
      profile = self.profiles[name]
      if 'extends' in profile:
        base = self.profiles[profile['extends']]
        profile = merge_dicts(base, profile)
        del profile['extends']
      self.apply(profile)
    except KeyError:
      raise VMRError(f'Unknown profile: {self.kind.id}/{name}')

  def reset(self):
    self.apply_profile('base')

  def __enter__(self):
    self._login()
    return self
  def __exit__(self, type, value, traceback):
    self._logout()


def _make_remote(kind):
  """
  Creates a new remote class and sets its number of inputs
  and outputs for a VM kind.
  
  The returned class will subclass VMRemote.
  """
  def init(self, *args, **kwargs):
    VMRemote.__init__(self, *args, **kwargs)
    self.kind = kind
    self.num_A, self.num_B = kind.layout
    self.inputs = tuple(InputStrip.make((i < self.num_A), self, i) for i in range(self.num_A+self.num_B))
    self.outputs = tuple(OutputBus.make((i < self.num_B), self, i) for i in range(self.num_A+self.num_B))
  def get_profiles(self):
    return profiles.profiles[kind.id]
 
  return type(f'VMRemote{kind.name}', (VMRemote,), {
    '__init__': init,
    'profiles': property(get_profiles)
  })

_remotes = {kind.id: _make_remote(kind) for kind in kinds.all}

def connect(kind_id, delay=None):
  """ Connect to Voicemeeter and sets its strip layout. """
  try:
    cls = _remotes[kind_id]
    return cls(delay=delay)
  except KeyError as err:
    raise VMRError(f'Invalid Voicemeeter kind: {kind_id}')

**Comment by LunaMeadows** [comment]
def exit(self, type, value, traceback):
self._logout()

this needs to be changed to 

def exit(self, type, value, traceback):
pass

Or copy and paste https://raw.githubusercontent.com/LunaMeadows/voicemeeter-remote-python/patch-3/voicemeeter/remote.py It is the updated remote.py that I have that should work for what you are wanting.

**Comment by Phoenix-64** [comment]
Thank you.
I am so sorry, I evidently edited the wrong remote.py
Now it works
