### ISSUE TITLE
python name 'null' is not defined

### ISSUE THREAD

**Issue by onyx-and-iris** [chvolkmann/voicemeeter-remote-python#9]
Hi, great work!

When I ran this script it threw an error 'python name 'null' is not defined'

In remote.py I changed to 

def connect(kind_id, delay=None):

Running Python 3.9.1 on Windows 10 Version 10.0.19042 Build 19042

**Comment by LunaMeadows** [comment]
Changing it to None should of fixed that, I have updated the code with the proper remote.py file. Try downloading and installing it again. If that does not work, we can go from there.

**Comment by onyx-and-iris** [comment]
Hey, thanks for the quick reply. Yes that did fix the issue. Thanks bud.
